project_id = "cxdkaxjeibqdmpvozirz"

[functions.fetch-link-preview]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.collect-analytics]
verify_jwt = false

[functions.og-post]
verify_jwt = false
