REVOKE EXECUTE ON FUNCTION public.can_post_in_group(uuid, uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.check_admin_access() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.get_conversation_member_role(uuid, uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.get_users_last_seen(uuid[]) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.has_active_vip(uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.has_role(uuid, public.app_role) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.has_stock_market_access(uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.is_admin(uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.is_admin_user() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.is_conversation_member(uuid, uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.is_group_admin(uuid, uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.is_group_member(uuid, uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.is_group_public(uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.is_order_creator(uuid, uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.is_order_participant(uuid, uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.is_user_admin(uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.user_exists_by_phone(text) FROM PUBLIC, anon;

GRANT EXECUTE ON FUNCTION public.can_post_in_group(uuid, uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.check_admin_access() TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.get_conversation_member_role(uuid, uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.get_users_last_seen(uuid[]) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.has_active_vip(uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.has_role(uuid, public.app_role) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.has_stock_market_access(uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.is_admin(uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.is_admin_user() TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.is_conversation_member(uuid, uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.is_group_admin(uuid, uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.is_group_member(uuid, uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.is_group_public(uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.is_order_creator(uuid, uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.is_order_participant(uuid, uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.is_user_admin(uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.user_exists_by_phone(text) TO authenticated, service_role;